name: draggable_list_view
description: "Draggable list view for Flutter"
version: 1.0.5
repository: https://github.com/yaroslav13/draggable_list_view.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

